name: Disable Workflow

on:
  push:
      branches: [ main ]

jobs:
  disable:
      run-on: ubantu-latesh

      steps:
         - name: Vijay Sagar
           run: echo "Disable Workflow Video Depops"
